name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@main

      - name: (env) setup node v${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          check-latest: true

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test:ci